# 파일 하나의 최대의 크기
spring.servlet.multipart.max-file-size=10MB

# multipart 요청 한번 당 전체의 최대 크기
spring.servlet.multipart.max-request-size=50MB

# 업로드 파일이 저장될 프로젝트 루트 기준 디렉터리
### 실제로 사용할때는 프로젝트 내부에 사용자들이 업로드 한것을 저장하지 않고, AWS S3(Simple Storage Service)을 사용하거나.. 한다. 지금은 실습
file.upload-dir=uploads
### multipart가 준비한 기능을 설정